### ISSUE TITLE
wrong comparePath

### ISSUE THREAD

**Issue by lolow** [jackjackk/gdxcompare#4] opened 2017-07-07 12:39 UTC

**Comment by jackjackk** [comment] 2017-07-07 14:24
I cannot reproduce! it should be opening the compare.html inside the same path of installation of gdxcompare, which in my case is anaconda/lib/site-packages/gdxcompare. You can check the installed files with: 
```
python -m pip show -f gdxcompare
```
what value is comparePath getting assigned to?

**Comment by lolow** [comment] 2017-07-07 14:42
now it is working after a reinstall.
thanks!

**Closed as completed** 2017-07-07 15:26 UTC
